# Generated by Django 5.0.6 on 2024-05-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0002_editora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
