# Generated by Django 5.0.6 on 2024-05-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0004_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nome',
        ),
    ]
